@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.solmaid.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;