@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.solmaid.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;